Add grpc support
vdaas/authorization-proxy pull request #2
Opened 2021-07-15 08:55 UTC by hlts2

# Description

_description_with_details_and_reasoning_

## Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Non-code changes (update documentation, pipeline, etc.)

### Flags

- [ ] breaks backward compatibility
- [ ] requires a documentation update
- [ ] has untestable code

## Related issue/PR

**Delete if not applicable**
- Fixes #_issue_
- Closes #_PR_

---

## Checklist

- [ ] Followed the guidelines in the CONTRIBUTING document
- [ ] Added prefix `[major]`/`[minor]`/`[patch]`/`[skip]` in the PR title
- [ ] Tested and linted the code
- [ ] Commented the code
- [ ] Made corresponding changes to the documentation
- [ ] Confirmed no dropping in test coverage (by [Codecov](https://codecov.io/gh/yahoojapan/authorization-proxy/pulls))
- [ ] Passed all pipeline checking
- [ ] Approved by >1 reviewer

## Checklist for maintainer
- [ ] Use `Squash and merge`
- [ ] Double-confirm the merge message has prefix `[major]`/`[minor]`/`[patch]`/`[skip]`
- [ ] Delete the branch after merge

2021-08-04 07:34 UTC, hlts2 commented on handler/grpc.go
> +// func NewGRPC(cfg config.Proxy, prov service.Authorizationd) *grpc.Server {
this is kpango's comment.
> we should delete this comment out

2021-08-04 07:36 UTC, hlts2 commented on usecase/authz_proxyd.go
>  			service.WithServerHandler(handler.New(cfg.Proxy, infra.NewBuffer(cfg.Proxy.BufferSize), athenz)),
this is kpango's comment.
> we should fix `WithServerHandler` to `WithRestHandler`.

2021-08-04 07:37 UTC, hlts2 commented on handler/grpc.go
> +func NewGRPC(cfg config.Proxy, roleCfg config.RoleToken, prov service.Authorizationd) grpc.StreamHandler {
this is kpango's comment.
> we should pass with fop.

2021-08-05 05:26 UTC, kevindiu commented on handler/grpc.go
> +func NewGRPC(cfg config.Proxy, roleCfg config.RoleToken, prov service.Authorizationd) grpc.StreamHandler {
fixed

2021-08-11 01:05 UTC, kpango requested changes

2021-08-11 01:05 UTC, kpango commented on service/server.go
> +	lfn := func() (net.Listener, error) {
Since the function lfn is not called in many places, I think this function variable is unnecessary.

2021-08-11 01:05 UTC, kpango commented on service/server.go
> +			grpc.UnknownServiceHandler(s.grpcHandler),
do we need tls credentials for proxy???

2021-08-11 01:05 UTC, kpango commented on service/server.go
> +func (s *server) listenAndGRPCServeAPI() (err error) {
why....
```suggestion
func (s *server) listenAndServeGRPCAPI() (err error) {
```

2021-08-11 01:19 UTC, vankichi reviewed
LGTM except others' comments.

2021-08-11 07:33 UTC, kevindiu commented on service/server.go
> +			gsech <- s.listenAndGRPCServeAPI()
fixed

2021-08-11 07:33 UTC, kevindiu commented on service/server.go
> +			sech <- s.listenAndServeAPI()
fixed

2021-08-11 07:37 UTC, kevindiu commented on service/server.go
> +	lfn := func() (net.Listener, error) {
fixed

2021-08-11 07:38 UTC, kevindiu commented on service/server.go
> +func (s *server) listenAndGRPCServeAPI() (err error) {
fixed

2021-08-11 09:31 UTC, hlts2 commented on service/server.go
> +			grpc.UnknownServiceHandler(s.grpcHandler),
yes, we need tls credentials for proxy. 
I have fixed: https://github.com/vdaas/authorization-proxy/pull/2/commits/b6dda50363a0f6de6cd78b5ddff54ab2220ed4a1

2021-08-11 09:31 UTC, hlts2 commented on service/server.go
> +func (s *server) listenAndGRPCServeAPI() (err error) {
https://github.com/vdaas/authorization-proxy/pull/2/commits/8d1f2089b8203038270d49385ec10451d4f62049

2021-08-11 09:31 UTC, hlts2 commented on service/server.go
> +	lfn := func() (net.Listener, error) {
https://github.com/vdaas/authorization-proxy/pull/2/commits/8d1f2089b8203038270d49385ec10451d4f62049

2021-08-11 09:31 UTC, hlts2 commented on service/server.go
> +			sech <- s.listenAndServeAPI()
https://github.com/vdaas/authorization-proxy/pull/2/commits/8d1f2089b8203038270d49385ec10451d4f62049

2021-08-11 09:32 UTC, hlts2 commented on service/server.go
> +			gsech <- s.listenAndGRPCServeAPI()
https://github.com/vdaas/authorization-proxy/pull/2/commits/8d1f2089b8203038270d49385ec10451d4f62049

2021-08-11 09:32 UTC, hlts2 commented on config/config.go
> +	HTTP Mode = "http"
https://github.com/vdaas/authorization-proxy/pull/2/commits/8d1f2089b8203038270d49385ec10451d4f62049

2021-08-12 01:58 UTC, rinx commented on handler/error.go
> +	ErrGRPCMetadataNotFound = "grpc metadata not found"
It seems that it is not used in anywhere.

2021-08-12 03:35 UTC, hlts2 commented on handler/error.go
> +	ErrGRPCMetadataNotFound = "grpc metadata not found"
thank you for your review.
I have fixed: https://github.com/vdaas/authorization-proxy/pull/2/commits/1d418dc578000789d5ef5f3493bcf2922b791acb

2021-08-25 05:21 UTC, kpango commented on handler/grpc.go
> +		conn, err := grpc.DialContext(ctx, target, dialOpts...)
I think it would be better to reuse dial connection for each targets.

2021-09-09 01:44 UTC, kpango approved these changes
LGTM

2021-09-09 02:01 UTC, kmrmt approved these changes

2021-09-09 02:25 UTC, rinx commented
BTW, is it able to start both REST proxy and gRPC proxy simultaneously?

2021-09-14 01:19 UTC, kevindiu commented
@rinx no, we will not support this use case.

2021-09-14 02:06 UTC, vankichi approved these changes

2021-09-14 02:26 UTC, rinx commented on service/server.go
> +	grpcCloser     io.Closer
If it is not able to run both the REST and the gRPC proxy, it is better to adding a new interface to unify them.
```go
type server struct {
	// authorization proxy server
	srv        newinterface.Server
	srvHandler newinterface.Handler
	srvRunning bool
	srvCloser     io.Closer
```

2021-09-21 06:49 UTC, kevindiu commented on service/server.go
> +	grpcCloser     io.Closer
It required structure code changes and the original source code from Athenz team, which we want to avoid it.
Can we just let it be and let Athenz team to decide it?

2021-09-27 01:34 UTC, datelier approved these changes

2021-09-27 01:37 UTC, rinx commented on service/server.go
> +	grpcCloser     io.Closer
okay.

2021-09-27 01:38 UTC, rinx approved these changes

2021-09-30 05:29 UTC, closed without merging